### ISSUE TITLE
Some errors with Aurora nightly app config

### ISSUE THREAD

**Issue by Go-rom** [ImranR98/apps.obtainium.imranr.dev#179]
Hello,

when i import Aurora nightly app config, i've got a pop up saying 

> Some Errors Occured
> could not determine release version.

The app still appears in the list but the download fails : 

> Unexpected error
> RangeError (start): Invalid value : Not in inclusive range 0..1:-1

Any idea how to solve this one please ?

Phone : S22+ running android 14
Obtainium always up to date.

**Comment by Hamster45105** [comment]
Hi!

[This config](https://apps.obtainium.imranr.dev/redirect?r=obtainium://app/%7B%22id%22%3A%22com.aurora.store.nightly%22%2C%22url%22%3A%22https%3A%2F%2Fauroraoss.com%2FAuroraStore%2FNightly%22%2C%22author%22%3A%22auroraoss.com%22%2C%22name%22%3A%22Aurora%20Store%22%2C%22preferredApkIndex%22%3A0%2C%22additionalSettings%22%3A%22%7B%5C%22intermediateLink%5C%22%3A%5B%5D%2C%5C%22customLinkFilterRegex%5C%22%3A%5C%22%5C%22%2C%5C%22filterByLinkText%5C%22%3Afalse%2C%5C%22skipSort%5C%22%3Afalse%2C%5C%22reverseSort%5C%22%3Afalse%2C%5C%22sortByLastLinkSegment%5C%22%3Afalse%2C%5C%22versionExtractWholePage%5C%22%3Afalse%2C%5C%22requestHeader%5C%22%3A%5B%7B%5C%22requestHeader%5C%22%3A%5C%22User-Agent%3A%20Mozilla%2F5.0%20(Linux%3B%20Android%2010%3B%20K)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F114.0.0.0%20Mobile%20Safari%2F537.36%5C%22%7D%5D%2C%5C%22defaultPseudoVersioningMethod%5C%22%3A%5C%22partialAPKHash%5C%22%2C%5C%22trackOnly%5C%22%3Afalse%2C%5C%22versionExtractionRegEx%5C%22%3A%5C%22(%5C%5C%5C%5Cd%7B2%7D)-(%5C%5C%5C%5Cd%7B2%7D)-(%5C%5C%5C%5Cd%7B4%7D)%5C%22%2C%5C%22matchGroupToUse%5C%22%3A%5C%22%5C%22%2C%5C%22versionDetection%5C%22%3Afalse%2C%5C%22useVersionCodeAsOSVersion%5C%22%3Afalse%2C%5C%22apkFilterRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22invertAPKFilter%5C%22%3Afalse%2C%5C%22autoApkFilterByArch%5C%22%3Atrue%2C%5C%22appName%5C%22%3A%5C%22Aurora%20Store%20Nightly%5C%22%2C%5C%22shizukuPretendToBeGooglePlay%5C%22%3Afalse%2C%5C%22exemptFromBackgroundUpdates%5C%22%3Afalse%2C%5C%22skipUpdateNotifications%5C%22%3Afalse%2C%5C%22about%5C%22%3A%5C%22Aurora%20Store%20Nightly%20is%20the%20test%20version%20of%20an%20unofficial%20FOSS%20client%20for%20Google%20Play%20with%20bare%20minimum%20features.%20Aurora%20Store%20allows%20users%20to%20download%2C%20update%2C%20and%20search%20for%20apps%20like%20the%20Play%20Store.%20It%20works%20perfectly%20fine%20with%20or%20without%20Google%20Play%20Services%20or%20microG.%5C%22%7D%22%2C%22overrideSource%22%3Anull%7D) should work. Make sure to refresh Obtainium before trying to install.

**Comment by Go-rom** [comment]
It works perfectly, thank you @Hamster45105 👍🏻

**Comment by Go-rom** [comment]
Hello @Hamster45105 

I'm sorry to bother you again but another related issue recently raised.

Now Obtainium thinks that the latest version is 31-08-2024 but as you can see by yourself : https://auroraoss.com/downloads/AuroraStore/Nightly/  there are nightlies in September too.

FYI, that kind of issue had been already spotted here https://github.com/ImranR98/Obtainium/issues/1659#issuecomment-2240441077

Any clue on your side on why Obtainium can't detect versions starting September 1st ?

Thank you

**Comment by Hamster45105** [comment]
Hi @Go-rom,

Yes that still applies. Unfortunately, I don't think there's much we can do as they are sorted weirdly. It may be necessary to open an issue on the [Aurora Store GitLab](https://gitlab.com/AuroraOSS/AuroraStore/-/issues). That being said, debug releases are also available on [this page](https://gitlab.com/AuroraOSS/AuroraStore/-/packages/24103616), so if support was added for this kind of GitLab page, debug versions could be downloaded from there.

**Comment by Go-rom** [comment]
Ok thank you, i'll see what i can do with Aurora team.

@ImranR98  would you be ok to re-open this issue please ?

**Comment by Go-rom** [comment]
Some news related to the [opened ticket](https://gitlab.com/AuroraOSS/AuroraStore/-/issues/1171) 

Rahul said that he'll take a look at the sorting issue and Aayush have just added auto-update feature to Aurora Nightly app.

**Comment by DwainZwerg** [comment]
@Hamster45105 Cool! Great news! Could you also add the new config to [your last, not yet accepted pull-request](https://github.com/ImranR98/apps.obtainium.imranr.dev/pull/229)?

**Comment by Go-rom** [comment]
> That's great!
> 
> I also found a JSON file that always has the newest nightly version so [this new config](https://apps.obtainium.imranr.dev/redirect?r=obtainium://app/%7B%22id%22%3A%22com.aurora.store.nightly%22%2C%22url%22%3A%22https%3A%2F%2Fauroraoss.com%2Fdownloads%2FAuroraStore%2FFeeds%2Fnightly_feed.json%22%2C%22author%22%3A%22auroraoss.com%22%2C%22name%22%3A%22Aurora%20Store%22%2C%22preferredApkIndex%22%3A0%2C%22additionalSettings%22%3A%22%7B%5C%22intermediateLink%5C%22%3A%5B%5D%2C%5C%22customLinkFilterRegex%5C%22%3A%5C%22%5C%22%2C%5C%22filterByLinkText%5C%22%3Afalse%2C%5C%22skipSort%5C%22%3Afalse%2C%5C%22reverseSort%5C%22%3Afalse%2C%5C%22sortByLastLinkSegment%5C%22%3Afalse%2C%5C%22versionExtractWholePage%5C%22%3Atrue%2C%5C%22requestHeader%5C%22%3A%5B%7B%5C%22requestHeader%5C%22%3A%5C%22User-Agent%3A%20Mozilla%2F5.0%20(Linux%3B%20Android%2010%3B%20K)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F114.0.0.0%20Mobile%20Safari%2F537.36%5C%22%7D%5D%2C%5C%22defaultPseudoVersioningMethod%5C%22%3A%5C%22partialAPKHash%5C%22%2C%5C%22trackOnly%5C%22%3Afalse%2C%5C%22versionExtractionRegEx%5C%22%3A%5C%22%5C%5C%5C%5Cd%7B2%7D-%5C%5C%5C%5Cd%7B2%7D-%5C%5C%5C%5Cd%7B4%7D%5C%22%2C%5C%22matchGroupToUse%5C%22%3A%5C%22%5C%22%2C%5C%22versionDetection%5C%22%3Afalse%2C%5C%22useVersionCodeAsOSVersion%5C%22%3Afalse%2C%5C%22apkFilterRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22invertAPKFilter%5C%22%3Afalse%2C%5C%22autoApkFilterByArch%5C%22%3Atrue%2C%5C%22appName%5C%22%3A%5C%22%5C%22%2C%5C%22shizukuPretendToBeGooglePlay%5C%22%3Afalse%2C%5C%22allowInsecure%5C%22%3Afalse%2C%5C%22exemptFromBackgroundUpdates%5C%22%3Afalse%2C%5C%22skipUpdateNotifications%5C%22%3Afalse%2C%5C%22about%5C%22%3A%5C%22%5C%22%2C%5C%22supportFixedAPKURL%5C%22%3Afalse%7D%22%2C%22overrideSource%22%3Anull%7D) should always work if you still want to get updates through Obtainium.

Hello @Hamster45105 

thank you for this new script.
It seems that the JSON file has appeared along with the self-update feature introduced in the nightly. (assumption based on [this commit](https://gitlab.com/AuroraOSS/AuroraStore/-/commit/2ece7ad2eacc749a8384e77b41e16f03d577f81c))

Unfortunately, that file is now stuck with the nightly release the 26th.
I asked Aayush about this status.

**Comment by Go-rom** [comment]
The issue with https://auroraoss.com/downloads/AuroraStore/Feeds/nightly_feed.json has been fixed by Aurora Store team
Self-update feature needs more time to be fixed but since the dedicated script for Obtainium works well now, this topic can be marked as resolved.
Thank you @Hamster45105 @ImranR98 👍🏻

**Comment by Flashwalker** [comment]
> That's great!
> 
> I also found a JSON file that always has the newest nightly version so [this new config](https://apps.obtainium.imranr.dev/redirect?r=obtainium://app/%7B%22id%22%3A%22com.aurora.store.nightly%22%2C%22url%22%3A%22https%3A%2F%2Fauroraoss.com%2Fdownloads%2FAuroraStore%2FFeeds%2Fnightly_feed.json%22%2C%22author%22%3A%22auroraoss.com%22%2C%22name%22%3A%22Aurora%20Store%22%2C%22preferredApkIndex%22%3A0%2C%22additionalSettings%22%3A%22%7B%5C%22intermediateLink%5C%22%3A%5B%5D%2C%5C%22customLinkFilterRegex%5C%22%3A%5C%22%5C%22%2C%5C%22filterByLinkText%5C%22%3Afalse%2C%5C%22skipSort%5C%22%3Afalse%2C%5C%22reverseSort%5C%22%3Afalse%2C%5C%22sortByLastLinkSegment%5C%22%3Afalse%2C%5C%22versionExtractWholePage%5C%22%3Atrue%2C%5C%22requestHeader%5C%22%3A%5B%7B%5C%22requestHeader%5C%22%3A%5C%22User-Agent%3A%20Mozilla%2F5.0%20(Linux%3B%20Android%2010%3B%20K)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F114.0.0.0%20Mobile%20Safari%2F537.36%5C%22%7D%5D%2C%5C%22defaultPseudoVersioningMethod%5C%22%3A%5C%22partialAPKHash%5C%22%2C%5C%22trackOnly%5C%22%3Afalse%2C%5C%22versionExtractionRegEx%5C%22%3A%5C%22%5C%5C%5C%5Cd%7B2%7D-%5C%5C%5C%5Cd%7B2%7D-%5C%5C%5C%5Cd%7B4%7D%5C%22%2C%5C%22matchGroupToUse%5C%22%3A%5C%22%5C%22%2C%5C%22versionDetection%5C%22%3Afalse%2C%5C%22useVersionCodeAsOSVersion%5C%22%3Afalse%2C%5C%22apkFilterRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22invertAPKFilter%5C%22%3Afalse%2C%5C%22autoApkFilterByArch%5C%22%3Atrue%2C%5C%22appName%5C%22%3A%5C%22%5C%22%2C%5C%22shizukuPretendToBeGooglePlay%5C%22%3Afalse%2C%5C%22allowInsecure%5C%22%3Afalse%2C%5C%22exemptFromBackgroundUpdates%5C%22%3Afalse%2C%5C%22skipUpdateNotifications%5C%22%3Afalse%2C%5C%22about%5C%22%3A%5C%22%5C%22%2C%5C%22supportFixedAPKURL%5C%22%3Afalse%7D%22%2C%22overrideSource%22%3Anull%7D) should always work if you still want to get updates through Obtainium.

Fail, can't find release. 
Wrong version regex.
Use one of these:
```
\d{2}\.\d{2}\.\d{4}
[0-9]+\.[0-9]+\.[0-9]+

```

~❗️Also for some reason [this release feed](https://auroraoss.com/downloads/AuroraStore/Feeds/release_feed.json) feeds not the latest release (4.7.5 instead of 4.8.1) 
Here is the json so you can obtain 4.8.1 
https://fars.ee/cWIT.json~
[Proper config](https://apps.obtainium.imranr.dev/redirect?r=obtainium://app/%7B%22id%22%3A%22com.aurora.store%22%2C%22url%22%3A%22https%3A%2F%2Fauroraoss.com%2Fapi%2Ffiles%22%2C%22author%22%3A%22auroraoss.com%22%2C%22name%22%3A%22Aurora%20Store%22%2C%22preferredApkIndex%22%3A0%2C%22additionalSettings%22%3A%22%7B%5C%22intermediateLink%5C%22%3A%5B%5D%2C%5C%22customLinkFilterRegex%5C%22%3A%5C%22%2Fdownloads%2FAuroraStore%2FRelease%2FAuroraStore-%5C%5C%5C%5Cd%5C%5C%5C%5C.%5C%5C%5C%5Cd%5C%5C%5C%5C.%5C%5C%5C%5Cd%5C%5C%5C%5C.apk%5C%22%2C%5C%22filterByLinkText%5C%22%3Afalse%2C%5C%22skipSort%5C%22%3Afalse%2C%5C%22reverseSort%5C%22%3Afalse%2C%5C%22sortByLastLinkSegment%5C%22%3Afalse%2C%5C%22versionExtractWholePage%5C%22%3Afalse%2C%5C%22requestHeader%5C%22%3A%5B%7B%5C%22requestHeader%5C%22%3A%5C%22User-Agent%3A%20Mozilla%2F5.0%20(Linux%3B%20Android%2010%3B%20K)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F114.0.0.0%20Mobile%20Safari%2F537.36%5C%22%7D%5D%2C%5C%22defaultPseudoVersioningMethod%5C%22%3A%5C%22partialAPKHash%5C%22%2C%5C%22trackOnly%5C%22%3Afalse%2C%5C%22versionExtractionRegEx%5C%22%3A%5C%22%5C%5C%5C%5Cd%5C%5C%5C%5C.%5C%5C%5C%5Cd%5C%5C%5C%5C.%5C%5C%5C%5Cd%5C%22%2C%5C%22matchGroupToUse%5C%22%3A%5C%22%5C%22%2C%5C%22versionDetection%5C%22%3Atrue%2C%5C%22useVersionCodeAsOSVersion%5C%22%3Afalse%2C%5C%22apkFilterRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22invertAPKFilter%5C%22%3Afalse%2C%5C%22autoApkFilterByArch%5C%22%3Atrue%2C%5C%22appName%5C%22%3A%5C%22Aurora%20Store%5C%22%2C%5C%22appAuthor%5C%22%3A%5C%22auroraoss.com%5C%22%2C%5C%22shizukuPretendToBeGooglePlay%5C%22%3Afalse%2C%5C%22allowInsecure%5C%22%3Afalse%2C%5C%22exemptFromBackgroundUpdates%5C%22%3Afalse%2C%5C%22skipUpdateNotifications%5C%22%3Afalse%2C%5C%22about%5C%22%3A%5C%22Aurora%20Store%20is%20an%20unofficial%20FOSS%20client%20for%20Google%20Play%20with%20bare%20minimum%20features.%20Aurora%20Store%20allows%20users%20to%20download%2C%20update%2C%20and%20search%20for%20apps%20like%20the%20Play%20Store.%20It%20works%20perfectly%20fine%20with%20or%20without%20Google%20Play%20Services%20or%20microG.%5C%22%2C%5C%22refreshBeforeDownload%5C%22%3Afalse%7D%22%2C%22overrideSource%22%3Anull%7D)
