### ISSUE TITLE
Add app that are not in F-Droid

### ISSUE THREAD

**Issue by atlantis451** [ImranR98/apps.obtainium.imranr.dev#227]
https://gitlab.com/fdroid/rfp/-/issues/?sort=created_date&state=all
[Issues](https://gitlab.com/fdroid/rfp/-/issues/?sort=created_date&state=all) in the crawler f-droid.  Extract `source code` url

Many of the apps in “issues” that do not meet the f-droid inclusion policy have not yet been added to F-Droid.

**Comment by DwainZwerg** [comment]
Hi @atlantis451,
this is what Obtainium is built for ("Get Android app updates straight from the source"). So why don't you just add the source URL (GitHub, GitLab, Forgejo (Codeberg) or SourceForge) so that you get the app directly from the developer instead of from F-Droid?

- [request for F-Droid](https://gitlab.com/fdroid/rfp/-/issues/2873)		**•** [Releases published by the developer directly at the source](https://github.com/C9-Labs/newsdrip/releases)

**Comment by DwainZwerg** [comment]
> It is still necessary to crawl f-droid Issues under the web crawler.

Why? What advantage do you have if F-Droid issues are crawled (apart from the fact that you can't download an APK from there anyway)?

> Add the app to apps.obtainium.imranr.dev

Apps that can simply be added to Obtainium (insert GitHub link in the source URL line; no further settings required) will not be added to the website.

**Comment by ImranR98** [comment]
Yes, the site is mainly for users who already know what they want but don't know how to add it. Adding thousands of apps isn't necessarily a good thing since the UI is very simple - there's no algorithm, ratings, etc. to make navigating through so many apps easy.
