### ISSUE TITLE
Could we add PPSSPP developement builds by making Obtainium get the configuration directly from the build site?

### ISSUE THREAD

**Issue by ghost** [ImranR98/apps.obtainium.imranr.dev#329]
https://builds.ppsspp.org/builds hosts the developement builds. Could we use some fancy regex to get PPSSPP developement builds from there?

**Comment by Hamster45105** [comment]
That URL leads to a 403 error

**Comment by DarkCrypt** [comment]
This has been requested multiple times.

This is the link for the dev builds: https://www.ppsspp.org/devbuilds/

This link can't be scraped because of JavaScript.

Other links:
- https://builds.ppsspp.org/meta/status.json
- https://builds.ppsspp.org/meta/history.json
- https://builds.ppsspp.org/meta/history-20.json

These 3 links have APKs but can't be scraped because of incomplete URLs.
