### ISSUE TITLE
MacroDroid

### ISSUE THREAD

**Issue by wertzuz** [ImranR98/apps.obtainium.imranr.dev#354]
Imported MacroDroid config does not recognise newest version of MacroDroid. Newest should be 5.49, but 5.48.13 is marked as Latest Release version in obtainium.

**Comment by DarkCrypt** [comment]
The 1st intermediate link slightly changed with v5.49. All previous 1st intermediate links had a capital "V" (V5.48) and this version has a lower case "v" (v5.49) which broke the config for this release.

In order to fix this we need to add `|v` to the 1st intermediate link. This will detect both the capital and lower case letter as a fail safe.

Present 1st Intermediate Link: `^V[0-9]+\.[0-9]+$`

Revised 1st Intermediate Link: `^V|v[0-9]+\.[0-9]+$`

@DwainZwerg or @Hamster45105
Suggested fix for the config website.

**Comment by DwainZwerg** [comment]
See https://github.com/ImranR98/apps.obtainium.imranr.dev/pull/356

**Comment by DwainZwerg** [comment]
@wertzuz Can you please close the issue as resolved?
